import type { Deck, SimpleCard } from "./types";

const cards: SimpleCard[] = [
  // ── Operating Systems ─────────────────────────────────────────────────────
  {
    id: "csf-c01",
    type: "simple",
    category: "operating-systems",
    front: "What is a process?",
    back: "A running instance of a program with its own memory space, resources, and execution state",
    options: [
      "A function call inside a program",
      "A running instance of a program with its own memory space, resources, and execution state",
      "A single thread of execution",
      "A scheduled OS system call",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c02",
    type: "simple",
    category: "operating-systems",
    front: "What is the key difference between a process and a thread?",
    back: "Threads share memory within a process; processes have separate memory spaces",
    options: [
      "Processes are faster than threads",
      "Threads share memory within a process; processes have separate memory spaces",
      "Processes share memory; threads do not",
      "There is no difference — they are the same",
    ],
    answerIndex: 1,
    explanation: "Threads within the same process share heap, code, and global data but have their own stack and registers.",
  },
  {
    id: "csf-c03",
    type: "simple",
    category: "operating-systems",
    front: "What is a deadlock?",
    back: "When two or more threads are blocked forever, each waiting for a resource held by the other",
    options: [
      "A program that runs infinitely without stopping",
      "When two or more threads are blocked forever, each waiting for a resource held by the other",
      "A type of race condition",
      "When a process consumes too much CPU",
    ],
    answerIndex: 1,
    explanation: "Deadlocks require four conditions: mutual exclusion, hold and wait, no preemption, and circular wait.",
  },
  {
    id: "csf-c04",
    type: "simple",
    category: "operating-systems",
    front: "What is virtual memory?",
    back: "An OS abstraction that gives each process the illusion of a large, private address space larger than physical RAM",
    options: [
      "Extra RAM added via hardware",
      "An OS abstraction that gives each process the illusion of a large, private address space larger than physical RAM",
      "A type of CPU cache",
      "Memory stored on the GPU",
    ],
    answerIndex: 1,
    explanation: "Virtual memory uses paging/swapping to map virtual addresses to physical RAM, allowing processes to use more memory than physically available.",
  },
  {
    id: "csf-c05",
    type: "simple",
    category: "operating-systems",
    front: "What is a race condition?",
    back: "When a program's output depends on the unpredictable timing or ordering of concurrent operations",
    options: [
      "A CPU performance benchmark",
      "When a program's output depends on the unpredictable timing or ordering of concurrent operations",
      "A scheduling algorithm that prioritizes fast processes",
      "When two threads run on different CPU cores",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c06",
    type: "simple",
    category: "operating-systems",
    front: "What is the purpose of a mutex?",
    back: "To ensure only one thread can access a critical section (shared resource) at a time",
    options: [
      "To terminate threads that take too long",
      "To ensure only one thread can access a critical section (shared resource) at a time",
      "To schedule CPU time across threads",
      "To manage memory allocation on the heap",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c07",
    type: "simple",
    category: "operating-systems",
    front: "What is paging in an operating system?",
    back: "Dividing memory into fixed-size blocks (pages) to manage virtual memory and reduce fragmentation",
    options: [
      "Scrolling through memory addresses sequentially",
      "Dividing memory into fixed-size blocks (pages) to manage virtual memory and reduce fragmentation",
      "A CPU cache eviction policy",
      "A process scheduling method",
    ],
    answerIndex: 1,
    explanation: "Paging maps virtual pages to physical frames, allowing non-contiguous physical memory to appear contiguous to the process.",
  },

  // ── Networking ────────────────────────────────────────────────────────────
  {
    id: "csf-c08",
    type: "simple",
    category: "networking",
    front: "What is the difference between TCP and UDP?",
    back: "TCP is reliable, ordered, and connection-based; UDP is faster but offers no delivery guarantee",
    options: [
      "TCP is faster; UDP is more reliable",
      "TCP is reliable, ordered, and connection-based; UDP is faster but offers no delivery guarantee",
      "TCP is for video streaming; UDP is for web browsing",
      "They are the same protocol with different names",
    ],
    answerIndex: 1,
    explanation: "TCP uses handshaking and acknowledgements; UDP just sends datagrams and moves on. Use TCP for accuracy (HTTP), UDP for speed (live video, gaming).",
  },
  {
    id: "csf-c09",
    type: "simple",
    category: "networking",
    front: "What does DNS do?",
    back: "Translates human-readable domain names (e.g., google.com) into IP addresses",
    options: [
      "Routes data packets across the internet",
      "Translates human-readable domain names (e.g., google.com) into IP addresses",
      "Assigns dynamic IP addresses to devices",
      "Encrypts network traffic end-to-end",
    ],
    answerIndex: 1,
    explanation: "DNS stands for Domain Name System — essentially the phonebook of the internet.",
  },
  {
    id: "csf-c10",
    type: "simple",
    category: "networking",
    front: "What HTTP status code means \"Not Found\"?",
    back: "404",
    options: ["200", "301", "404", "500"],
    answerIndex: 2,
    explanation: "200 = OK, 301 = Moved Permanently, 404 = Not Found, 500 = Internal Server Error.",
  },
  {
    id: "csf-c11",
    type: "simple",
    category: "networking",
    front: "What is a REST API?",
    back: "An architectural style for stateless web APIs that uses standard HTTP methods (GET, POST, PUT, DELETE)",
    options: [
      "A database query language",
      "An architectural style for stateless web APIs that uses standard HTTP methods (GET, POST, PUT, DELETE)",
      "A binary network protocol",
      "A server-side rendering framework",
    ],
    answerIndex: 1,
    explanation: "REST (Representational State Transfer) APIs are stateless — each request contains all info needed to process it.",
  },
  {
    id: "csf-c12",
    type: "simple",
    category: "networking",
    front: "What is the purpose of a load balancer?",
    back: "To distribute incoming traffic across multiple servers to improve availability and performance",
    options: [
      "To compress network packets",
      "To distribute incoming traffic across multiple servers to improve availability and performance",
      "To encrypt data between client and server",
      "To assign IP addresses to new devices",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c13",
    type: "simple",
    category: "networking",
    front: "What is latency in networking?",
    back: "The time it takes for a packet to travel from source to destination",
    options: [
      "The amount of data transferred per second (throughput)",
      "The time it takes for a packet to travel from source to destination",
      "The number of packets dropped during transmission",
      "The maximum bandwidth of a network connection",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c14",
    type: "simple",
    category: "networking",
    front: "What does HTTPS add over HTTP?",
    back: "TLS/SSL encryption — data in transit is encrypted and the server's identity is verified",
    options: [
      "Faster data transfer speeds",
      "TLS/SSL encryption — data in transit is encrypted and the server's identity is verified",
      "Support for larger file uploads",
      "Automatic compression of all responses",
    ],
    answerIndex: 1,
    explanation: "HTTPS = HTTP + TLS. It protects against eavesdropping and man-in-the-middle attacks.",
  },

  // ── Databases ─────────────────────────────────────────────────────────────
  {
    id: "csf-c15",
    type: "simple",
    category: "databases",
    front: "What does ACID stand for in databases?",
    back: "Atomicity, Consistency, Isolation, Durability",
    options: [
      "Availability, Consistency, Integrity, Durability",
      "Atomicity, Consistency, Isolation, Durability",
      "Atomicity, Concurrency, Integrity, Distribution",
      "Availability, Concurrency, Isolation, Durability",
    ],
    answerIndex: 1,
    explanation: "ACID properties guarantee that database transactions are processed reliably even in the event of errors or system failures.",
  },
  {
    id: "csf-c16",
    type: "simple",
    category: "databases",
    front: "What is a database index?",
    back: "A data structure that speeds up query lookups at the cost of extra storage and slower writes",
    options: [
      "A list of all tables in the database",
      "A data structure that speeds up query lookups at the cost of extra storage and slower writes",
      "The primary key of a table",
      "A foreign key constraint",
    ],
    answerIndex: 1,
    explanation: "Indexes (e.g., B-trees) allow the DB to find rows without scanning the whole table. They speed up reads but slow down inserts/updates.",
  },
  {
    id: "csf-c17",
    type: "simple",
    category: "databases",
    front: "What is the difference between SQL and NoSQL databases?",
    back: "SQL uses structured tables with fixed schemas; NoSQL uses flexible schemas (documents, key-value, graph, etc.)",
    options: [
      "SQL is always faster than NoSQL",
      "SQL uses structured tables with fixed schemas; NoSQL uses flexible schemas (documents, key-value, graph, etc.)",
      "NoSQL databases support transactions; SQL databases do not",
      "They are the same — NoSQL is just a newer version of SQL",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c18",
    type: "simple",
    category: "databases",
    front: "What is a primary key?",
    back: "A column (or set of columns) that uniquely identifies each row in a table",
    options: [
      "The first column defined in a table",
      "A column (or set of columns) that uniquely identifies each row in a table",
      "A foreign key pointing to another table",
      "An auto-incrementing integer column",
    ],
    answerIndex: 1,
  },
  {
    id: "csf-c19",
    type: "simple",
    category: "databases",
    front: "What does a SQL JOIN do?",
    back: "Combines rows from two or more tables based on a related column",
    options: [
      "Deletes matching rows from multiple tables at once",
      "Combines rows from two or more tables based on a related column",
      "Sorts query results by multiple columns",
      "Creates a new table from an existing one",
    ],
    answerIndex: 1,
    explanation: "Common types: INNER JOIN (only matching rows), LEFT JOIN (all left + matching right), FULL OUTER JOIN (all rows from both).",
  },
  {
    id: "csf-c20",
    type: "simple",
    category: "databases",
    front: "What is database normalization?",
    back: "Organizing a database to reduce redundancy and ensure data integrity by splitting data into related tables",
    options: [
      "Converting all string values to lowercase",
      "Organizing a database to reduce redundancy and ensure data integrity by splitting data into related tables",
      "Optimizing queries by adding indexes",
      "Replicating a database across multiple servers",
    ],
    answerIndex: 1,
    explanation: "Normal forms (1NF, 2NF, 3NF, BCNF) each remove a different type of data redundancy or anomaly.",
  },
];

export const builtinCsFundamentalsDeck: Deck = {
  id: "builtin-cs-fundamentals",
  name: "CS Fundamentals",
  description: "Operating systems, networking, and databases — the building blocks of software engineering.",
  createdAt: "2026-01-01T00:01:00.000Z",
  isBuiltIn: true,
  categories: ["operating-systems", "networking", "databases"],
  cards,
};
