import type { Deck, SimpleCard } from "./types";

const cards: SimpleCard[] = [
  // ── Algorithms ────────────────────────────────────────────────────────────
  {
    id: "algo-c01",
    type: "simple",
    category: "algorithms",
    front: "What is the time complexity of binary search?",
    back: "O(log n)",
    options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
    answerIndex: 1,
    explanation: "Binary search halves the search space on each step, giving O(log n) time.",
  },
  {
    id: "algo-c02",
    type: "simple",
    category: "algorithms",
    front: "What is the average time complexity of QuickSort?",
    back: "O(n log n)",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    answerIndex: 1,
    explanation: "QuickSort averages O(n log n) but degrades to O(n²) in the worst case (e.g., already-sorted input with a bad pivot).",
  },
  {
    id: "algo-c03",
    type: "simple",
    category: "algorithms",
    front: "Which sorting algorithm is stable and always guarantees O(n log n)?",
    back: "Merge Sort",
    options: ["QuickSort", "HeapSort", "Merge Sort", "Bubble Sort"],
    answerIndex: 2,
    explanation: "Merge Sort is stable (equal elements keep their order) and always O(n log n), unlike QuickSort (unstable, O(n²) worst) or HeapSort (unstable).",
  },
  {
    id: "algo-c04",
    type: "simple",
    category: "algorithms",
    front: "What does it mean for a sorting algorithm to be \"stable\"?",
    back: "Equal elements maintain their original relative order",
    options: [
      "The algorithm never crashes",
      "Equal elements maintain their original relative order",
      "The algorithm runs in constant time",
      "The algorithm uses O(1) extra space",
    ],
    answerIndex: 1,
  },
  {
    id: "algo-c05",
    type: "simple",
    category: "algorithms",
    front: "What is the space complexity of Merge Sort?",
    back: "O(n)",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 2,
    explanation: "Merge Sort requires O(n) auxiliary space for the temporary arrays used during merging.",
  },
  {
    id: "algo-c06",
    type: "simple",
    category: "algorithms",
    front: "What algorithm finds the shortest path in an unweighted graph?",
    back: "BFS (Breadth-First Search)",
    options: ["DFS", "BFS (Breadth-First Search)", "Dijkstra's", "Bellman-Ford"],
    answerIndex: 1,
    explanation: "BFS explores nodes level by level, so the first time it reaches a node is always via the shortest path in an unweighted graph.",
  },
  {
    id: "algo-c07",
    type: "simple",
    category: "algorithms",
    front: "What is dynamic programming?",
    back: "Breaking a problem into overlapping subproblems and caching results to avoid redundant computation",
    options: [
      "A type of recursion with no base case",
      "Breaking a problem into overlapping subproblems and caching results to avoid redundant computation",
      "A graph traversal technique",
      "A divide-and-conquer strategy that never reuses results",
    ],
    answerIndex: 1,
  },
  {
    id: "algo-c08",
    type: "simple",
    category: "algorithms",
    front: "What is the time complexity of inserting into a balanced BST?",
    back: "O(log n)",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
    explanation: "A balanced BST (e.g., AVL, Red-Black) maintains O(log n) height, so insert, search, and delete are all O(log n).",
  },
  {
    id: "algo-c09",
    type: "simple",
    category: "algorithms",
    front: "What is the best-case time complexity of Bubble Sort (with early exit)?",
    back: "O(n)",
    options: ["O(1)", "O(n)", "O(n log n)", "O(n²)"],
    answerIndex: 1,
    explanation: "With an early-exit flag, Bubble Sort stops after one pass if no swaps occurred — O(n) on an already-sorted array.",
  },
  {
    id: "algo-c10",
    type: "simple",
    category: "algorithms",
    front: "What is the purpose of Big-O notation?",
    back: "To describe how an algorithm's time or space grows relative to input size, in the worst case",
    options: [
      "To measure exact execution time in milliseconds",
      "To describe how an algorithm's time or space grows relative to input size, in the worst case",
      "To count the total number of operations exactly",
      "To compare memory usage across programming languages",
    ],
    answerIndex: 1,
  },

  // ── Data Structures ───────────────────────────────────────────────────────
  {
    id: "algo-c11",
    type: "simple",
    category: "data-structures",
    front: "What is the time complexity of accessing an element in an array by index?",
    back: "O(1)",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    answerIndex: 0,
    explanation: "Arrays store elements contiguously in memory, so index access is a single pointer arithmetic operation — O(1).",
  },
  {
    id: "algo-c12",
    type: "simple",
    category: "data-structures",
    front: "What data structure uses LIFO (Last In, First Out)?",
    back: "Stack",
    options: ["Queue", "Stack", "Heap", "Deque"],
    answerIndex: 1,
  },
  {
    id: "algo-c13",
    type: "simple",
    category: "data-structures",
    front: "What data structure uses FIFO (First In, First Out)?",
    back: "Queue",
    options: ["Stack", "Queue", "Priority Queue", "Circular Buffer"],
    answerIndex: 1,
  },
  {
    id: "algo-c14",
    type: "simple",
    category: "data-structures",
    front: "What is the average time complexity of HashMap.get()?",
    back: "O(1)",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 0,
    explanation: "Hash maps compute the bucket index via hashing — O(1) on average. Worst case is O(n) if all keys collide into one bucket.",
  },
  {
    id: "algo-c15",
    type: "simple",
    category: "data-structures",
    front: "What property defines a Binary Search Tree (BST)?",
    back: "All left descendants < node < all right descendants",
    options: [
      "Each node has exactly two children",
      "All left descendants < node < all right descendants",
      "The tree is perfectly balanced",
      "Nodes are stored in sorted order level by level",
    ],
    answerIndex: 1,
  },
  {
    id: "algo-c16",
    type: "simple",
    category: "data-structures",
    front: "What is a linked list's time complexity for accessing the k-th element?",
    back: "O(n)",
    options: ["O(1)", "O(log n)", "O(n)", "O(k)"],
    answerIndex: 2,
    explanation: "Linked lists must be traversed from the head; there is no direct index access, so it's O(n) in the worst case.",
  },
  {
    id: "algo-c17",
    type: "simple",
    category: "data-structures",
    front: "What data structure is typically used to implement a priority queue?",
    back: "Heap (min-heap or max-heap)",
    options: ["Stack", "Queue", "Heap (min-heap or max-heap)", "BST"],
    answerIndex: 2,
    explanation: "A heap allows O(log n) insert and O(1) peek at the min/max, making it ideal for priority queues.",
  },
  {
    id: "algo-c18",
    type: "simple",
    category: "data-structures",
    front: "What is a trie (prefix tree) used for?",
    back: "Efficient string prefix search and autocomplete",
    options: [
      "Sorting integers in O(n) time",
      "Efficient string prefix search and autocomplete",
      "Shortest path in a graph",
      "Storing key-value pairs with O(1) access",
    ],
    answerIndex: 1,
    explanation: "A trie stores strings character by character; prefix lookups are O(m) where m is the prefix length, independent of the number of stored strings.",
  },
  {
    id: "algo-c19",
    type: "simple",
    category: "data-structures",
    front: "What is the main advantage of a doubly linked list over a singly linked list?",
    back: "Traversal in both directions; O(1) deletion when you have a pointer to the node",
    options: [
      "Faster random access",
      "Traversal in both directions; O(1) deletion when you have a pointer to the node",
      "Less memory usage per node",
      "O(1) access by index",
    ],
    answerIndex: 1,
  },
  {
    id: "algo-c20",
    type: "simple",
    category: "data-structures",
    front: "What is a graph?",
    back: "A set of nodes (vertices) connected by edges, which may be directed or undirected",
    options: [
      "A sorted tree structure",
      "A set of nodes (vertices) connected by edges, which may be directed or undirected",
      "A type of hash map",
      "A linear sequence of elements",
    ],
    answerIndex: 1,
  },
];

export const builtinAlgorithmsDeck: Deck = {
  id: "builtin-algorithms-ds",
  name: "Algorithms & Data Structures",
  description: "Big-O, sorting, searching, and core data structures — essential for technical interviews.",
  createdAt: "2026-01-01T00:00:00.000Z",
  isBuiltIn: true,
  categories: ["algorithms", "data-structures"],
  cards,
};
