"use client";

import { useState, useMemo, useEffect, Suspense } from "react";
import Link from "next/link";
import { useSearchParams, useRouter } from "next/navigation";
import { useDecks } from "@/hooks/useDecks";
import { QuizCardView } from "@/components/quiz/QuizCardView";
import { QuizTypeModal } from "@/components/quiz/QuizTypeModal";
import { ProgressBar } from "@/components/ui/ProgressBar";
import { CategoryFilter } from "@/components/ui/CategoryFilter";
import { ScoreSummary } from "@/components/ui/ScoreSummary";
import { generateQuestionsForDeck, getCategoryLabel } from "@/lib/utils";
import type { Card, QuestionType } from "@/lib/types";
import type { AnswerRecord } from "@/app/decks/[id]/quiz/page";

function CrossDeckQuizInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { allDecks, hydrated } = useDecks();

  const selectedCats = useMemo(
    () => (searchParams.get("cats") ?? "").split(",").filter(Boolean),
    [searchParams]
  );

  // Redirect if no categories
  useEffect(() => {
    if (hydrated && selectedCats.length === 0) {
      router.replace("/study");
    }
  }, [hydrated, selectedCats.length, router]);

  // Aggregate cards + deck name/id lookup
  const { sessionCards, cardDeckMap, cardDeckIdMap } = useMemo(() => {
    const nameMap: Record<string, string> = {};
    const idMap: Record<string, string> = {};
    const cards: Card[] = allDecks.flatMap((d) =>
      d.cards
        .filter((c) => selectedCats.includes(c.category))
        .map((c) => {
          nameMap[c.id] = d.name;
          idMap[c.id] = d.id;
          return c;
        })
    );
    return { sessionCards: cards, cardDeckMap: nameMap, cardDeckIdMap: idMap };
  }, [allDecks, selectedCats]);
  // cardDeckMap is keyed by card.id; cloze questions use originalCardId to look up the right entry

  const [selectedTypes, setSelectedTypes] = useState<QuestionType[] | null>(null);
  const [randomize, setRandomize] = useState(false);
  const [activeCategory, setActiveCategory] = useState<string | null>(null);
  const [answers, setAnswers] = useState<Record<string, AnswerRecord>>({});
  const [showSummary, setShowSummary] = useState(false);

  useEffect(() => {
    const label = selectedCats.map(getCategoryLabel).join(", ");
    document.title = `Study: ${label} — Quiz · kwek`;
  }, [selectedCats]);

  const allQuestions = useMemo(() => {
    if (!selectedTypes) return [];
    return generateQuestionsForDeck(sessionCards, selectedTypes, randomize, false);
  }, [sessionCards, selectedTypes, randomize]);

  const sessionCats = useMemo(
    () => [...new Set(sessionCards.map((c) => c.category))],
    [sessionCards]
  );

  const questions = useMemo(() => {
    if (!activeCategory) return allQuestions;
    return allQuestions.filter((q) => {
      const card = sessionCards.find((c) => c.id === (q.originalCardId ?? q.cardId));
      return card?.category === activeCategory;
    });
  }, [allQuestions, activeCategory, sessionCards]);

  if (!hydrated) {
    return (
      <div className="max-w-3xl mx-auto px-5 py-10">
        <div className="text-muted text-sm">Loading…</div>
      </div>
    );
  }

  const backHref = `/study?cats=${selectedCats.join(",")}`;

  function handleStart(types: QuestionType[], rand: boolean) {
    setSelectedTypes(types);
    setRandomize(rand);
    setAnswers({});
    setShowSummary(false);
  }

  function handleAnswer(cardId: string, value: number | string, isCorrect: boolean) {
    setAnswers((prev) => {
      if (prev[cardId] !== undefined) return prev;
      const next = { ...prev, [cardId]: { value, isCorrect } };
      if (Object.keys(next).length === questions.length) {
        setTimeout(() => setShowSummary(true), 800);
      }
      return next;
    });
  }

  function handleCategoryChange(cat: string | null) {
    setActiveCategory(cat);
    setAnswers({});
    setShowSummary(false);
  }

  function handleRestart() {
    setSelectedTypes(null);
    setRandomize(false);
    setAnswers({});
    setShowSummary(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function handleReviewMistakes() {
    const wrongCardIds = [...new Set(
      Object.entries(answers)
        .filter(([, a]) => !a.isCorrect)
        .map(([qCardId]) => {
          const q = questions.find((q) => q.cardId === qCardId);
          return q?.originalCardId ?? qCardId;
        })
    )];
    const entries = wrongCardIds
      .map((cardId) => ({ deckId: cardDeckIdMap[cardId], cardId }))
      .filter((e) => !!e.deckId);
    sessionStorage.setItem(
      "kwek:quiz-mistakes",
      JSON.stringify({ entries, backHref })
    );
    router.push("/review?mistakes=1");
  }

  const answeredCount = Object.keys(answers).length;
  const score = Object.values(answers).filter((a) => a.isCorrect).length;
  const hasAutoGenerated = questions.some((q) => q.isGenerated);

  return (
    <div className="max-w-3xl mx-auto px-5 py-10 pb-16">
      {/* Nav */}
      <div className="mb-6">
        <Link
          href={backHref}
          className="font-mono text-[0.7rem] font-semibold uppercase tracking-widest text-muted hover:text-text-primary transition-colors"
        >
          ← Study
        </Link>
      </div>

      {/* Header */}
      <div className="mb-6 pb-4 border-b border-border">
        <h1 className="text-xl font-extrabold tracking-tight text-text-primary">
          Quiz Mode
          <span className="ml-2 text-base font-normal text-muted">
            — {selectedCats.map(getCategoryLabel).join(", ")}
          </span>
        </h1>
        {selectedTypes && hasAutoGenerated && (
          <p className="text-xs text-muted mt-1.5 font-medium">
            ✦ Some questions were auto-generated from your flashcards
          </p>
        )}
      </div>

      {/* Type selection modal */}
      {!selectedTypes && (
        <QuizTypeModal
          onStart={handleStart}
          cardCount={sessionCards.length}
          customQuizCount={0}
        />
      )}

      {/* Quiz content */}
      {selectedTypes && (
        <>
          <ProgressBar
            current={answeredCount}
            total={questions.length}
            showScore
            score={score}
          />

          <CategoryFilter
            categories={sessionCats}
            active={activeCategory}
            onChange={handleCategoryChange}
          />

          {showSummary && (
            <ScoreSummary
              score={score}
              total={questions.length}
              deckId="cross-deck"
              deckName={selectedCats.map(getCategoryLabel).join(", ")}
              onRestart={handleRestart}
              backHref={backHref}
              backLabel="Back to Study"
              wrongCount={questions.length - score}
              onReviewMistakes={handleReviewMistakes}
            />
          )}

          {questions.length === 0 ? (
            <div className="text-center py-16">
              <p className="text-muted text-sm">
                No cards in this {activeCategory ? "category" : "selection"}.
              </p>
            </div>
          ) : (
            questions.map((question, idx) => (
              <div key={question.cardId}>
                {cardDeckMap[question.originalCardId ?? question.cardId] && (
                  <p className="text-[0.7rem] font-mono font-semibold text-muted mt-5 mb-1">
                    {cardDeckMap[question.originalCardId ?? question.cardId]}
                  </p>
                )}
                <QuizCardView
                  question={question}
                  questionNumber={idx + 1}
                  total={questions.length}
                  answered={answers[question.cardId] ?? null}
                  onAnswer={(value, isCorrect) =>
                    handleAnswer(question.cardId, value, isCorrect)
                  }
                />
              </div>
            ))
          )}
        </>
      )}
    </div>
  );
}

export default function CrossDeckQuizPage() {
  return (
    <Suspense fallback={<div className="max-w-3xl mx-auto px-5 py-10 text-muted text-sm">Loading…</div>}>
      <CrossDeckQuizInner />
    </Suspense>
  );
}
