"use client";

import { use, useState, useMemo } from "react";
import Link from "next/link";
import { useDecks } from "@/hooks/useDecks";
import { QuizCardView } from "@/components/quiz/QuizCardView";
import { QuizTypeModal } from "@/components/quiz/QuizTypeModal";
import { ProgressBar } from "@/components/ui/ProgressBar";
import { CategoryFilter } from "@/components/ui/CategoryFilter";
import { ScoreSummary } from "@/components/ui/ScoreSummary";
import { generateQuestionsForDeck } from "@/lib/utils";
import { hasQuizData } from "@/lib/types";
import type { Category, QuestionType } from "@/lib/types";

interface PageProps {
  params: Promise<{ id: string }>;
}

export type AnswerRecord = { value: number | string; isCorrect: boolean };

export default function QuizPage({ params }: PageProps) {
  const { id } = use(params);
  const { getDeckById, hydrated } = useDecks();
  const deck = getDeckById(id);

  const [selectedTypes, setSelectedTypes] = useState<QuestionType[] | null>(null);
  const [randomize, setRandomize] = useState(false);
  const [customOnly, setCustomOnly] = useState(false);
  const [activeCategory, setActiveCategory] = useState<Category | null>(null);
  const [answers, setAnswers] = useState<Record<string, AnswerRecord>>({});
  const [showSummary, setShowSummary] = useState(false);

  const allQuestions = useMemo(() => {
    if (!deck || !selectedTypes) return [];
    const cards = customOnly ? deck.cards.filter(hasQuizData) : deck.cards;
    const overrideManual = !customOnly && selectedTypes.length === 1 && !selectedTypes.includes("mc");
    return generateQuestionsForDeck(cards, selectedTypes, randomize, overrideManual);
  }, [deck, selectedTypes, randomize, customOnly]);

  const questions = useMemo(() => {
    if (!activeCategory) return allQuestions;
    return allQuestions.filter((q) => {
      const card = deck?.cards.find((c) => c.id === q.cardId);
      return card?.category === activeCategory;
    });
  }, [allQuestions, activeCategory, deck]);

  if (!hydrated) {
    return (
      <div className="max-w-3xl mx-auto px-5 py-10">
        <div className="text-muted text-sm">Loading…</div>
      </div>
    );
  }

  if (!deck) {
    return (
      <div className="max-w-3xl mx-auto px-5 py-10">
        <Link href="/" className="font-mono text-[0.7rem] font-semibold uppercase tracking-widest text-muted hover:text-text-primary">
          ← Home
        </Link>
        <p className="mt-8 text-muted">Deck not found.</p>
      </div>
    );
  }

  const customQuizCount = deck.cards.filter(hasQuizData).length;

  function handleStart(types: QuestionType[], rand: boolean, useCustomOnly = false) {
    setSelectedTypes(types);
    setRandomize(rand);
    setCustomOnly(useCustomOnly);
    setAnswers({});
    setShowSummary(false);
  }

  function handleAnswer(cardId: string, value: number | string, isCorrect: boolean) {
    setAnswers((prev) => {
      if (prev[cardId] !== undefined) return prev;
      const next = { ...prev, [cardId]: { value, isCorrect } };
      if (Object.keys(next).length === questions.length) {
        setTimeout(() => setShowSummary(true), 800);
      }
      return next;
    });
  }

  function handleCategoryChange(cat: Category | null) {
    setActiveCategory(cat);
    setAnswers({});
    setShowSummary(false);
  }

  function handleRestart() {
    setSelectedTypes(null);
    setRandomize(false);
    setCustomOnly(false);
    setAnswers({});
    setShowSummary(false);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  const answeredCount = Object.keys(answers).length;
  const score = Object.values(answers).filter((a) => a.isCorrect).length;
  const hasAutoGenerated = questions.some((q) => q.isGenerated);

  return (
    <div className="max-w-3xl mx-auto px-5 py-10 pb-16">
      {/* Nav */}
      <div className="mb-6">
        <Link
          href={`/decks/${id}`}
          className="font-mono text-[0.7rem] font-semibold uppercase tracking-widest text-muted hover:text-text-primary transition-colors"
        >
          ← {deck.name}
        </Link>
      </div>

      {/* Header */}
      <div className="mb-6 pb-4 border-b border-border">
        <h1 className="text-xl font-extrabold tracking-tight text-text-primary">
          Quiz Mode
          <span className="ml-2 text-base font-normal text-muted">— {deck.name}</span>
        </h1>
        {selectedTypes && hasAutoGenerated && !customOnly && (
          <p className="text-xs text-muted mt-1.5 font-medium">
            ✦ Some questions were auto-generated from your flashcards
          </p>
        )}
        {selectedTypes && customOnly && (
          <p className="text-xs text-muted mt-1.5 font-medium">
            ✦ Using your {customQuizCount} custom question{customQuizCount !== 1 ? "s" : ""}
          </p>
        )}
      </div>

      {/* Type selection modal */}
      {!selectedTypes && (
        <QuizTypeModal
          onStart={handleStart}
          cardCount={deck.cards.length}
          customQuizCount={customQuizCount}
        />
      )}

      {/* Quiz content */}
      {selectedTypes && (
        <>
          {/* Progress */}
          <ProgressBar
            current={answeredCount}
            total={questions.length}
            showScore
            score={score}
          />

          {/* Category filter */}
          <CategoryFilter
            categories={deck.categories}
            active={activeCategory}
            onChange={handleCategoryChange}
          />

          {/* Score summary */}
          {showSummary && (
            <ScoreSummary
              score={score}
              total={questions.length}
              deckId={id}
              deckName={deck.name}
              onRestart={handleRestart}
            />
          )}

          {/* Questions */}
          {questions.length === 0 ? (
            <div className="text-center py-16">
              <p className="text-muted text-sm">No cards in this {activeCategory ? "category" : "deck"}.</p>
            </div>
          ) : (
            questions.map((question, idx) => (
              <QuizCardView
                key={question.cardId}
                question={question}
                questionNumber={idx + 1}
                total={questions.length}
                answered={answers[question.cardId] ?? null}
                onAnswer={(value, isCorrect) => handleAnswer(question.cardId, value, isCorrect)}
              />
            ))
          )}
        </>
      )}
    </div>
  );
}
